version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASWORD: password 
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '3000:5432'
  server:
    image: postgres-crud
    depends_on:
      - db
    ports:
      - '5000:5000'