version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3000:5432'
  cache:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - '3001:6379'
  server:
    image: postgres-crud
    environment:
      POSTGRES_DB: db
      REDIS_CACHE: cache
    build: './'
    depends_on:
      - db
      - cache
    ports:
      - '5000:5000'