version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3000:5432'
  server:
    image: postgres-crud
    build: './'
    depends_on:
      - db
    ports:
      - '5000:5000'